// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8psrVT8D5JZ0CkOsd5sIk3KnUxew5Av4',
    appId: '1:805906181872:web:27676dc74c0d40340d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    authDomain: 'actordb-cf981.firebaseapp.com',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
    measurementId: 'G-WYNXYWRRVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49SNiBnkHCxGoUZ0GrXEKMv0WoTanOqo',
    appId: '1:805906181872:android:eeec8ee078b0e4630d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_BQjS5zbW24Pj5wbdjcjbfYboCa_feU',
    appId: '1:805906181872:ios:a2dafa8584ed17dd0d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
    iosClientId: '805906181872-ai2a1k4rqe3n4ab5fr0pb5ujig4uad2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.uractor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_BQjS5zbW24Pj5wbdjcjbfYboCa_feU',
    appId: '1:805906181872:ios:a2dafa8584ed17dd0d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
    iosClientId: '805906181872-ai2a1k4rqe3n4ab5fr0pb5ujig4uad2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.uractor',
  );
}
