// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase has no Linux plugin, so the app is not built for Linux. '
          'See the Platforms section of README.md.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The key the desktop builds authenticate with.
  ///
  /// Every other key here is restricted to the callers allowed to use it: the
  /// web key by HTTP referrer, the Android key by package name and signing
  /// certificate, the iOS key by bundle identifier. A desktop app sends none
  /// of those three, so any of those restrictions refuses it with 403 before a
  /// password is looked at — every account, every correct password, alike.
  ///
  /// This key carries no application restriction, because that is the only
  /// setting a desktop caller can satisfy. It is restricted by API instead, to
  /// the services the app calls, and what stands between it and the data is
  /// `firestore.rules` rather than the question of who may hold the key.
  ///
  /// Do not point a desktop platform at one of the other keys to save adding
  /// one. That is the defect this replaced, and it fails identically on both
  /// desktop platforms while looking like a wrong password.
  static const String _desktopApiKey =
      'AIzaSyCpeLg1aoAJNTOWPTlPgGwR40JCA9047QM';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8psrVT8D5JZ0CkOsd5sIk3KnUxew5Av4',
    appId: '1:805906181872:web:27676dc74c0d40340d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    authDomain: 'actordb-cf981.firebaseapp.com',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
    measurementId: 'G-WYNXYWRRVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49SNiBnkHCxGoUZ0GrXEKMv0WoTanOqo',
    appId: '1:805906181872:android:eeec8ee078b0e4630d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_BQjS5zbW24Pj5wbdjcjbfYboCa_feU',
    appId: '1:805906181872:ios:a2dafa8584ed17dd0d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
    iosClientId:
        '805906181872-ai2a1k4rqe3n4ab5fr0pb5ujig4uad2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.uractor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _desktopApiKey,
    appId: '1:805906181872:ios:a2dafa8584ed17dd0d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
    iosClientId:
        '805906181872-ai2a1k4rqe3n4ab5fr0pb5ujig4uad2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.uractor',
  );

  /// Windows has no registration of its own in the Firebase console, so it
  /// borrows the web app's id — that part was never the problem. What it
  /// cannot borrow is the web key, which is restricted by HTTP referrer and
  /// refuses a caller that sends none.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _desktopApiKey,
    appId: '1:805906181872:web:27676dc74c0d40340d9c35',
    messagingSenderId: '805906181872',
    projectId: 'actordb-cf981',
    authDomain: 'actordb-cf981.firebaseapp.com',
    databaseURL: 'https://actordb-cf981-default-rtdb.firebaseio.com',
    storageBucket: 'actordb-cf981.appspot.com',
  );
}
